### ISSUE TITLE
Git LFS Files are broken

### ISSUE THREAD

**Issue by Mixone-FinallyHere** [herbertmilhomme/PokemonUnity#10]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Files like Scratch.png in Animation Sprites are broken
**Expected behavior:**
They should be there
- Platform (Win7, 8, 10? macOS? Linux distro? WebGL?):
Win 10

git lfs fetch retrurns 404

**Comment by Fallenleader** [comment]
Not sure if it is a problem inherent to LFS, but this project repo AFAIK doesn't use LFS (I haven't even set up LFS on my end and can pull just fine).
Also, the framework isn't ready to plug and build just yet, so be it 2D or 3D, you will have to work on the frontend yourself until we can get that portion done. WIthin a bit I will have a frontend for a stadium mode sample to work with, and within a few months a full overworld setup demonstration for 3D.
2D side can be adapted from this by anyone else who wants to do so later on, as it will be some minor changes to the frontend.

**Comment by herbertmilhomme** [comment]
@Mixone-FinallyHere I'm so sorry for delayed response, i didnt even see the notification or notice there was any other activity on project besides myself and Fallen. I hope you can forgive me and not assume it was because you were ignored.

To address your issue and clear confusion, the project DID contain LFS, once-upon-a-time. BUT the LFS caused the issues you mentioned, and was subsequently removed from the repository _because_ it was breaking images and preventing them from being useable on local/remote directories. If you're still encountering residues failures and errors because of that past mistake, forgive me, they must have been oversights. I made an attempt to recover all original assets and replace all those that were damaged or corrupted by the git feature. 

Solution: Just replace the asset (from internet), or update this thread for any others that you encounter, and i'll make commits to fix them.

LFS isnt a feature that is wanted in the repository, and has caused similar issue already, my solution was to get rid of it entirely, and replace all damaged or affected assets. (As far as i can tell, the only assets that were damaged and affected were images).


Fallen is correct in his reply and statements. The Unity side of the project hasnt received much attention and i feel it's very unfair to be responsible for it, as i've spent most of my time writing code and not much else. In future, i'll invest more time in sorting out assets and visuals, so that the framework project can be more inclusive.
